# Generated by Django 3.2.7 on 2021-10-02 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.host'),
        ),
        migrations.AddField(
            model_name='booking',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AddField(
            model_name='booking',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.host'),
        ),
    ]
